# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Dependabot configuration for Costco Schedule App
# React Native/Expo project with native iOS/Android components

version: 2
updates:
  # JavaScript/TypeScript dependencies (main project)
  - package-ecosystem: "npm"
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    # Allow patch and minor updates, be careful with major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore React packages that are pinned by Expo SDK 53
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-native"
      - dependency-name: "react-native-safe-area-context"
      - dependency-name: "react-native-screens"
      - dependency-name: "react-native-gesture-handler"
      - dependency-name: "react-native-reanimated"
      - dependency-name: "react-native-svg"
      - dependency-name: "react-native-webview"
      # Add other React Native packages that are managed by Expo SDK
      - dependency-name: "@react-native*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    # Group Expo SDK updates together
    groups:
      expo-sdk:
        patterns:
          - "expo*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native*"
          - "@react-native*"
      testing:
        patterns:
          - "*jest*"
          - "@testing-library/*"
          - "@types/jest"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3

  # Android Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 3
    # Be conservative with Android updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
