# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
 - package-ecosystem: "npm" # React Native/Expo mobile app
    directory: "/mobile" # Location of package.json
    schedule:
      interval: "weekly"
    # Only raise pull requests for security updates
    open-pull-requests-limit: 0
    # Enable security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
